### ISSUE TITLE
Running against a local sandbox

### ISSUE THREAD

**Issue by mckenzig** [flyteorg/flytekit-python-template#9]
Hi newbie question.

I have a local sandbox running as per:  https://docs.flyte.org/en/latest/getting_started.html

I have validated that I can access the console via http://localhost:30081/console

It is not clear to me which HOST:PORT to provide in the instructions provided in this README.md:

```
Register this template repo against your Flyte deployment like so, substituting whichever host:port combination you are using:
FLYTE_HOST=<host>:<port> make register
```

Do I need to specify host or port when running on my localhost?

I get an error below (I believe that the SSL error is a red herring and this is just attempting to connect to the wrong host/port):

```
make register
NOPUSH= IMAGE_NAME=flytekit-python-template flytekit_build_image.sh ./Dockerfile

------------------------------------
           DOCKER BUILD
------------------------------------

~/projects/flytekit-python-template ~/projects/flytekit-python-template

..........


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/projects/flytesnacks/.env/bin/flyte-cli", line 8, in <module>
    sys.exit(_flyte_cli())
  File "/home/ubuntu/projects/flytesnacks/.env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/projects/flytesnacks/.env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/projects/flytesnacks/.env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/projects/flytesnacks/.env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/projects/flytesnacks/.env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/projects/flytesnacks/.env/lib/python3.8/site-packages/flytekit/clis/flyte_cli/main.py", line 2310, in setup_config
    response = _requests.get(config_url)
  File "/home/ubuntu/projects/flytesnacks/.env/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ubuntu/projects/flytesnacks/.env/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/projects/flytesnacks/.env/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/projects/flytesnacks/.env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/projects/flytesnacks/.env/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=30081): Max retries exceeded with url: /config/v1/flyte_client (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))


```

**Comment by mckenzig** [comment]
Hmm maybe not a red herring, strace shows:
```

[pid 2917017] sendmsg(9, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\26\3\1\2\0\1\0\1\374\3\0033\221g\6\320\317\6\217'\234\1O\\\35\335[@\341\273v%"..., iov_len=517}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 517
[pid 2917017] epoll_wait(7, [{EPOLLIN|EPOLLOUT, {u32=37666064, u64=37666064}}], 100, 183) = 1
[pid 2917017] recvmsg(9, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="HTTP/1.1 400 Bad Request\r\nconten"..., iov_len=8192}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_TCP, cmsg_type=0x24}], msg_controllen=24, msg_flags=0}, 0) = 156
[pid 2917017] clock_gettime(CLOCK_REALTIME, {tv_sec=1624586430, tv_nsec=315267703}) = 0
[pid 2917017] gettid()                  = 2917017
[pid 2917017] write(2, "E0625 02:00:30.315267703 2917017"..., 181E0625 02:00:30.315267703 2917017 ssl_transport_security.cc:1468] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
) = 181
[pid 2917017] clock_gettime(CLOCK_REALTIME, {tv_sec=1624586430, tv_nsec=315525104}) = 0

```

**Comment by mckenzig** [comment]
Was able to workaround this by calling register-files with -i

`flyte-cli register-files -i -h localhost:30081  -p flyteexamples -d development -v 2670d9e8c3e973233d915081bb1e98111d97e547 /home/ubuntu/projects/flytekit-python-template/_pb_output/*`
